spring:
  application:
    name: ExKtorUnitTest


server:
  port: 8080
  shutdown: graceful
  compression:
    enabled: true
  error: # only dev
    include-message: always
    include-stacktrace: always
    include-exception: true
